### PR TITLE
Local attention implementation

### PR DESCRIPTION
**Pull request by kobecsb**
It's a implementation of local attention [1]. Tested in GPU. Please refere to the diff.
# gru_local_layer.
- usage arguments: 
  - decoder='gru_local', 
  - pos_win (INT)
  - src_maxlen (INT)
# References
[1] Luong M T, Pham H, Manning C D. Effective approaches to attention-based neural machine 
translation[J]. arXiv preprint arXiv:1508.04025, 2015.

### CODE REVIEW

**Comment by rsennrich** [comment]
Thank you for this pull request. The new option '--src_maxlen' seems confusing, since it only affects local attention. Any chance we could re-use the '--maxlen' argument?

**Comment by kobecsb** [comment]
yes. This argument is used to limit the length of source sentence. If the limitation is the same as target maxlen, we can totally reuse maxlen.

**Comment by rsennrich** [comment]
thanks; I pulled this, but I didn't test if/how well the local attention works.

**Comment by kobecsb** [comment]
Oh thsnk you! Local attention can avilliate the under and over translation in long sentences according to the paper and my experiments. But I think that adding my codes to a new branch, namely local-attention would be better. Sorry for the mis operation and trouble to you.

**Pull request merged**
