### PR TITLE
Shuffle without writing to tmp file first

### PR DESCRIPTION
**Pull request by jozef-mokry**
I think it is not necessary to write lines into a temporary file and then immediately read all lines from it. 
As a side effect, this update also helps when files contained  "|||" .

### CODE REVIEW

**Comment by rsennrich** [comment]
Hi Jozef,

I agree that the temporary file currently doesn't fulfill its purpose, since its content is loaded into memory anyway. Ideally, we would avoid having to load the full file into memory, since datasets can become quite large, but I don't know of any appropriate low-memory shuffle algorithms. Does anybody have a suggestion?

**Comment by kpu** [comment]
Use shuf --random-source and provide the same stream of random numbers?

**Comment by kpu** [comment]
`parallel --gnu "shuf --random-source=<(openssl enc -aes-256-ctr -pass pass:$RANDOM -nosalt </dev/zero 2>/dev/null) <"{} ">"{}.shuf ::: files`

**Comment by rsennrich** [comment]
thanks Kenneth - this is probably faster than shuffling in python, but still loads the whole file into memory.

**Pull request merged**
