### PR TITLE
Save adam's variables in checkpoints too

### PR DESCRIPTION
**Pull request by jozef-mokry**
I modified the train method such that params of Adam are also checkpointed. Would it be useful to have checkpointing for other optimization methods (rmsprop, adadelta) even though we always use Adam?

### CODE REVIEW

**Comment by jozef-mokry** [comment]
Yes, I tested the following:
- starting a new training with Adam
- starting a new training with Adadelta
- resuming from a checkpoint which contained Adam's parameters 
- resuming from a checkpoint which did not contain Adam's parameters

**Comment by rsennrich** [comment]
looks good - one nitpick is that translate.py / rescore.py / score.py currently also load all adam variables, so memory consumption is doubled. I added a quick fix for this.

**Comment by jozef-mokry** [comment]
Yes, that's a good point, thanks for the fix.

**Comment by rsennrich** [comment]
there was a concern that the model files are suddenly much larger, which is mildly inconvenient when distributing models etc.

How about we change this to save/read the optimizer variables in a separate file? This will make it easier to delete the variables if we don't need them, or to just copy the main model parameters.

**Comment by rsennrich** [comment]
Just FYI, I've now changed the code to save the historical gradient information for adam (or other optimizers that support saving) in a separate file ("filename.gradinfo.npz"). This will make it easier to delete this info if you don't need it. Loading is still supported for models that store the info in the file itself.

**Pull request merged**
